# Generated by Django 3.2.5 on 2022-01-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_basis', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cost',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_description', models.TextField()),
                ('check_in_time', models.CharField(max_length=30)),
                ('check_out_time', models.CharField(max_length=30)),
                ('base_num_people', models.IntegerField()),
                ('max_num_people', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('queen_bed', models.IntegerField()),
                ('single_bed', models.IntegerField()),
                ('double_bed', models.IntegerField()),
                ('policy', models.TextField()),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expression', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField(max_length=1000)),
                ('description_url', models.URLField(max_length=1000)),
                ('launched_at', models.DateTimeField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.admin')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stays.category')),
            ],
            options={
                'db_table': 'stays',
            },
        ),
        migrations.CreateModel(
            name='StayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.stay')),
            ],
            options={
                'db_table': 'stay_images',
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.cost')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.room')),
            ],
            options={
                'db_table': 'room_price',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.room')),
            ],
            options={
                'db_table': 'room_images',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.stay'),
        ),
    ]
